version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER # Set in project settings
          password: $DOCKER_HUB_PASSWORD

jobs:
  setup_environment:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Make Spike executable
          command: chmod +x Spike
      - run:
          name: Run Spike.py
          command: python Spike.py

  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: Custom script
          command: |
            echo "Hello, World!" # Add your script logic here

workflows:
  my-custom-workflow:
    jobs:
      - setup_environment
      - my-job-name
